#!/bin/sh

if [ "$1" = "start" ]
then
	if [ -e /boot/usbhost ]
	then
		exit 0
	fi
	. /etc/profile
	cd /sys/kernel/config/usb_gadget
	mkdir g0
	cd g0
	mkdir functions/acm.GS0
	mkdir configs/c.1
	ln -s functions/acm.GS0 configs/c.1/
	ls /sys/class/udc/ | cat > UDC
	echo device > /proc/cviusb/otg_role
fi
